---
- name: Template ossec.conf with Wazuh manager info
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: '0640'
  notify: restart wazuh-agent

- name: Ensure ossec group exists
  group:
    name: ossec
    state: present

- name: Ensure /var/ossec directory ownership and permissions
  file:
    path: /var/ossec
    recurse: yes
    owner: wazuh
    group: wazuh         # changed from wazuh to ossec
    mode: '0750'         # 750 is recommended for security, not 755

- name: Ensure /var/ossec/queue directory writable by group
  file:
    path: /var/ossec/queue
    recurse: yes
    mode: '2770'         # set gid bit + rwx for group to allow queue access

